In [1]:
import numpy

In [4]:
list1 = [1,2,3,4,5,"Hello"]

print(type(list1))

print(list1[3])

<class 'list'>
4


In [18]:
nd_list = numpy.array([1,24,4])

print(type(nd_list))
# print(nd_list[3])
print(nd_list.dtype)


<class 'numpy.ndarray'>
int64


In [16]:
nd_list[1:4]

array([24. ,  4. ,  5.2])

In [20]:
nd_list_2d = numpy.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [1,2,3],
    [4,5,6],
    [7,8,9]
])    

In [22]:
nd_list_2d[4][2]

np.int64(6)

In [27]:
one_dimension = numpy.array([[1,2,3,4,5]])

In [28]:
one_dimension.ndim

2

In [62]:
nd_list_2d.ndim

2

In [47]:
nd_list_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
nd_list_2d.ndim

2

In [29]:
nd_list_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
nd_list_2d.shape

(6, 3)

In [50]:
nd_list_2d.shape

(6, 3)

In [ ]:
18

1 * 18
3 * 9
3 * 6
6 * 3
9 * 2
18 * 1

In [38]:
nd_list_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
nd_list_2d.reshape((2,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [40]:
nd_list_2d.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
nd_list = numpy.array([1,2,3,4,5,6,7])

In [ ]:
nd_list

array([1, 2, 3, 4, 5, 6, 7])

In [59]:
nd_list_A = numpy.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])  

nd_list_B = numpy.array([
    [1],
    [2],
    [3]
])    

nd_list_A ** nd_list_B

array([[  1,   2,   3],
       [ 16,  25,  36],
       [343, 512, 729]])

In [60]:
nd_list_A = numpy.array([
    [1,2,3,5],
    [4,5,6,5],
    [7,8,9,5],
    [7,8,9,5],
])    

nd_list_B = numpy.array([
    [1,0,0,0],
    [0,1,0,0],
    [0,0,1,0],
    [0,0,0,1]
])    

nd_list_B.dot(nd_list_A)

array([[1, 2, 3, 5],
       [4, 5, 6, 5],
       [7, 8, 9, 5],
       [7, 8, 9, 5]])

In [62]:
nd_list_A.transpose()

array([[1, 4, 7, 7],
       [2, 5, 8, 8],
       [3, 6, 9, 9],
       [5, 5, 5, 5]])

In [56]:
nd_list_A.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
nd_list_A = numpy.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

nd_list_A.shape

(9,)

In [66]:
zeros = numpy.zeros((12,12))

In [67]:
zeros[3][3] = 12

In [68]:
zeros

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 12.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [58]:
nd_list_A.transpose()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
numpy.ones((15,15))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [60]:
numpy.zeros((16,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
0 to 10 5

0, 2.5, 5, 7.5, 10

In [71]:
(numpy.linspace(0,4578,48))

array([   0.        ,   97.40425532,  194.80851064,  292.21276596,
        389.61702128,  487.0212766 ,  584.42553191,  681.82978723,
        779.23404255,  876.63829787,  974.04255319, 1071.44680851,
       1168.85106383, 1266.25531915, 1363.65957447, 1461.06382979,
       1558.46808511, 1655.87234043, 1753.27659574, 1850.68085106,
       1948.08510638, 2045.4893617 , 2142.89361702, 2240.29787234,
       2337.70212766, 2435.10638298, 2532.5106383 , 2629.91489362,
       2727.31914894, 2824.72340426, 2922.12765957, 3019.53191489,
       3116.93617021, 3214.34042553, 3311.74468085, 3409.14893617,
       3506.55319149, 3603.95744681, 3701.36170213, 3798.76595745,
       3896.17021277, 3993.57446809, 4090.9787234 , 4188.38297872,
       4285.78723404, 4383.19148936, 4480.59574468, 4578.        ])